# Generated by Django 4.0.4 on 2022-10-09 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Departments',
            fields=[
                ('department_Id', models.AutoField(primary_key=True, serialize=False)),
                ('department_Name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Employees',
            fields=[
                ('employee_Id', models.AutoField(primary_key=True, serialize=False)),
                ('employee_Name', models.CharField(max_length=255)),
                ('department', models.CharField(max_length=255)),
                ('dateOfJoing', models.DateField()),
                ('photoFileName', models.CharField(max_length=255)),
            ],
        ),
    ]
